site_name: 2024.1 - CALCULUS

repo_name: '2024.1 - CALCULUS'
repo_url: 'https://github.com/fga-eps-mds/2024.1-CALCULUS-DOC'

theme:
  name: material
  palette:
    primary: white
    accent: black
    background: black
    text: white
    code: white
  font:
    text: Poppins
    code: Inconsolata
  font_size:
    text: 16px
    code: 14px

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: 'index.md'
  - Organizações do Projeto: 
    - Termo de Abertura do Projeto: 'organizacoes/tap.md'
    - Documento de Arquitetura: 'organizacoes/documento_arquitetura.md'
    - Estrutura Analítica do Projeto: 'organizacoes/eap.md'
  - Planejamentos: 
    - Quadro de disponibilidade: 'planejamento/quadro_de_disponibilidade.md'
    - Quadro de conhecimento e pareamento: 'planejamento/conhecimento_pareamento.md'
    - Agenda e Ritual da Equipe: 'planejamento/agenda_ritual.md'
    - Planejamento de Comunicação: 'planejamento/comunicacao.md'
  - Guias:
    - Guia de contribuição: 'guias/guia-contribuicao.md'
    - Código de conduta: 'guias/codigo-conduta.md'
    - Guia de estilo: 'guias/guia-estilo.md'
  - Planos:
    - Analise de Riscos: 'planos/planos_riscos.md'
    - Plano de qualidade: 'planos/plano_qualidade.md'
    - Plano de custos: 'planos/planos_custos.md'
  - Atas de Reunião:
    - Reunião 1 - 25/03: 'atas/reuniao1.md'
    - Reunião 2 - 01/04: 'atas/reuniao2.md'
    - Reunião 3 - 03/04: 'atas/reuniao3.md'
  - Dojo:
    - Dojo Markdown: 'dojo/dojo-markdown.md'
    - Dojo Git: 'dojo/dojo-git.md'
    - Dojo Docker: 'dojo/dojo-docker.md'
  - Lean Inception:
    - Visão do Produto: 'lean/visao_produto.md'
    - É - Não É - Faz - Não Faz: 'lean/faz_nao_faz.md'
    - Objetivos do Produto: 'lean/objetivos_produto.md'
    - Jornada: 'lean/jornada_usuário.md'
    - Revisão Técnica, de Negócio e de UX: 'lean/revisao_tecnica.md'
    - Sequenciador: 'lean/sequenciador.md'
    - Personas: 'lean/personas.md'
    - Brainstorm: 'lean/brainstorms_funcionalidades.md'
    - Canvas MVP: 'lean/canvas_mvp.md'
