site_name: 2024.1 - CALCULUS

repo_name: '2024.1 - CALCULUS'
repo_url: 'https://github.com/fga-eps-mds/2024.1-CALCULUS-DOC'

theme:
  name: material
  palette:
    primary: white
    accent: black
    background: black
    text: white
    code: white
  font:
    text: Poppins
    code: Inconsolata
  font_size:
    text: 16px
    code: 14px

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: 'index.md'
  - Lean Inception:
    - Visão do Produto: 'lean/visao_produto.md'
    - É - Não É - Faz - Não Faz: 'lean/faz_nao_faz.md'
    - Objetivos do Produto: 'lean/objetivos_produto.md'
    - Jornada: 'lean/jornada_usuário.md'
    - Revisão Técnica, de Negócio e de UX: 'lean/revisao_tecnica.md'
    - Sequenciador: 'lean/sequenciador.md'
    - Personas: 'lean/personas.md'
    - Brainstorm: 'lean/brainstorms_funcionalidades.md'
    - Canvas MVP: 'lean/canvas_mvp.md'
  - Documentação Técnica: 
    - Termo de Abertura do Projeto: 'organizacoes/tap.md'
    - Documento de Arquitetura: 'organizacoes/documento_arquitetura.md'
    - Estrutura Analítica do Projeto: 'organizacoes/eap.md'
    - Visão de Dados: 'organizacoes/visao-de-dados.md'
    - Visão de Endpoints: 'organizacoes/visao-de-endpoints.md'
  - Gestão do Projeto: 
    - Plano de Comunicação: 'planejamento/plano_comunicacao.md'
    - Plano de Qualidade: 'planos/plano_qualidade.md'
    - Plano de Custos: 'planos/planos_custos.md'
    - Analise de Riscos: 'planos/planos_riscos.md'
    - Quadro de Conhecimento e Pareamento: 'planejamento/conhecimento_pareamento.md'
  - Guias:
    - Guia de Contribuição: 'guias/guia-contribuicao.md'
    - Guia de Estilo: 'guias/guia-estilo.md'
    - Código de Conduta: 'guias/codigo-conduta.md'
  - Dojos:
    - Dojo Markdown: 'dojo/dojo-markdown.md'
    - Dojo Git: 'dojo/dojo-git.md'
    - Dojo Docker: 'dojo/dojo-docker.md'
    - Dojo Frontend: 'dojo/dojo-frontend.md'

