site_name: 2024.1 - CALCULUS

repo_name: '2024.1 - CALCULUS'
repo_url: 'https://github.com/fga-eps-mds/2024.1-CALCULUS-DOC'

theme:
  name: material
  palette:
    primary: white
    accent: black
    background: black
    text: white
    code: white
  font:
    text: Poppins
    code: Inconsolata
  font_size:
    text: 16px
    code: 14px

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: 'index.md'
  - Planejamento: 
    - Quadro de disponibilidade: 'planejamento/quadro_de_disponibilidade.md'
    - Quadro de conhecimento: 'planejamento/heatmap.md'
  - Guias:
    - Guia de contribuição: 'guias/guia-contribuicao.md'
    - Código de conduta: 'guias/codigo-conduta.md'
  - Atas de Reunião:
    - Reunião 1 - 25/03: 'atas/reuniao1.md'
    - Reunião 2 - 01/04: 'atas/reuniao2.md'
    - Reunião 3 - 03/04: 'atas/reuniao3.md'
  - Dojo:
    - Dojo Markdown: 'dojo/dojo-markdown.md'
  - Lean Inception:
    - Visão do Produto: 'lean/visao_produto.md'
    - É - Não É - Faz - Não Faz: 'lean/faz_nao_faz.md'
    - Objetivos do Produto: 'lean/objetivos_produto.md'
    - Personas: 'lean/personas.md'
    - Brainstorm: 'lean/brainstorms_funcionalidades.md'
